### ISSUE TITLE
Add JSON Schema and .md file describing ASR message format

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-speech#42]
@vincentraymond-ua - can you add a directory called `message_specs` at the top level of the repo and add two files: `asr_message.json` and `asr_message.md` in that folder that contain a description of the ASR agent output format? See here for an example: https://gitlab.asist.aptima.com/asist/testbed/-/tree/master/MessageSpecs/Lever.

**Comment by vincentraymond-ua** [comment]
Yes, I will start working on this.
